apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dinendash
type: Opaque
stringData:
  # Auth service
  SECRET_KEY: "mkBtKXz5ItNbEH9O9LK71FMp2rH95tEja0Ijo_oIkXE"
  DB_NAME: "auth_db"
  API_KEY: "5b3ce3597851110001cf6248ee5a7a86129a47428d23c9e22dcc9cb2"

  # Tracking service
  TRACKING_DB_NAME: "tracking_db"
  TRACKING_MONGO_URI: "mongodb://tracking-mongo:27017"
