apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mongo-pvc
  namespace: dinendash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracking-mongo-pvc
  namespace: dinendash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
